language: java
addons:
  sonarcloud:
    organization: "flaviolazzarini"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - cd gateway
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=flaviolazzarini_microservices-sample
