version: '3.2'

networks:
 backend:

services:

#  app:
#    image: order_management
#    restart: always
#    networks:
#      - backend

  mongodb:
    container_name: order_mongo
    image: hub.edu.abiz.ch/appe/system/mongodb:stable
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-viewer:
    image: hub.edu.abiz.ch/appe/system/mongodb-viewer:stable
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=order_mongo
    networks:
      - backend
    links:
      - mongodb

